spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 0

logging:
  level:
    root: info

hashgenerator:
  batch-size: 100
  threadpool-size: 5
  threadpool-queue-capacity: 100

hash:
  maxRange: 10000
  batchSize: 1000